version: "2"

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/mickamy/pointless

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - revive
    - gosec
    - unconvert
    - unparam
    - prealloc
    - bodyclose
    - nilerr
    - wrapcheck
    - nlreturn
    - godot
    - paralleltest
    - forcetypeassert

  settings:
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: increment-decrement
        - name: var-naming
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
    gosec:
      excludes:
        - G104

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
